import "./globals.css";
import Navbar from "@/Components/Navbar";
import localFont from 'next/font/local';

const lufga = localFont({
  src: [
    {
      path: "../../public/fonts/Lufga-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Lufga-Bold.otf",
      weight: "700",
      style: "normal",
    }
  ],
  variable: "--font-lufga",
})

const helveticaNow = localFont({
  src: [
    {
      path: "../../public/fonts/HelveticaNowDisplay-Bold.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/HelveticaNowDisplay-Regular.woff2",
      weight: "700",
      style: "normal",
    }
  ],
  variable: "--font-helvetica-now",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lufga.variable} ${helveticaNow.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans antialiased">
        <Navbar></Navbar>
        <main>
        {children}
        </main>
        </body>
    </html>
  );
}
